var currencies = {
  "united arab emirates dirham": "aed",
  "arab dirham":"aed",
  "emirates dirham":"aed",
  "arab emirates dirham":"aed",
  "afghan afghani": "afn",
  "afghani":"afn",
  "afghanistan afghani":"afn",
  "albanian lek": "all",
  "albania lek": "all",
  "albani lek": "all",
  "lek":"all",
  "armenian dram": "amd",
  "armenia dram": "amd",
  "dram": "amd",
  "netherlands antillean guilder": "ang",
  "guilder":"ang",
  "netherlands guilder":"ang",
  "angolan kwanza":"aoa",
  "angola kwanza":"aoa",
  "kwanza":"aoa",
  "argentine peso":"ars",
  "australian dollar":"aud",
  "aruban florin":"awg",
  "florin":"awg",
  "azerbaijani manat":"azn",
  "azerbaijani new manat":"azn",
  "bosnia-herzegovina convertible mark":"bam",
  "bosnia and herzegovina convertible mark":"bam",
  "bosnia-herzegovina convertible marka":"bam",
  "bosnia and herzegovina convertible marka":"bam",
  "barbadian dollar":"bbd",
  "bangladeshi taka":"bdt",
  "bangladesh taka":"bdt",
  "taka":"bdt",
  "bulgarian lev":"bgn",
  "lev":"bgn",
  "bahraini dinar":"bhd",
  "bahrain dinar":"bhd",
  "burundian franc":"bif",
  "burundi franc":"bif",
  "bermudan dollar":"bmd",
  "brunei dollar":"bnd",
  "bolivian boliviano":"bob",
  "brazilian real":"brl",
  "real":"brl",
  "bahamian dollar":"bsd",
  "bitcoin":"btc",
  "bhutanese ngultrum":"btn",
  "botswanan pula":"bwp",
  "belarusian ruble":"byn",
  "belize dollar":"bzd",
  "canadian dollar":"cad",
  "congolese franc":"cdf",
  "swiss franc":"chf",
  "chilean unit of account":"clf",
  "chilean peso":"clp",
  "chinese yuan":"cny",
  "yuan":"cny",
  "colombian peso":"cop",
  "costa rican colon":"crc",
  "cuban convertible peso":"cuc",
  "cuban peso":"cup",
  "cape verdean escudo":"cve",
  "czech republic koruna":"czk",
  "koruna":"czk",
  "czech koruna":"czk",
  "djiboutian franc":"djf",
  "danish krone":"dkk",
  "dominican peso":"dop",
  "algerian dinar":"dzd",
  "estonian kroon":"eek",
  "egyptian pound":"egp",
  "eritrean nakfa":"ern",
  "ethiopian birr":"etb",
  "euro":"eur",
  "fijian dollar":"fjd",
  "falkland islands pound":"fkp",
  "british pound sterling":"gbp",
  "british pound":"gbp",
  "pound sterling":"gbp",
  "sterling":"gbp",
  "pound":"gbp",
  "georgian lari":"gel",
  "guernsey pound":"ggp",
  "ghanaian cedi":"ghs",
  "gibraltar pound":"gip",
  "gambian dalasi":"gmd",
  "guinean franc":"gnf",
  "guatemalan quetzal":"gtq",
  "guyanaese dollar":"gyd",
  "hong kong dollar":"hkd",
  "honduran lempira":"hnl",
  "croatian kuna":"hrk",
  "haitian gourde":"htg",
  "hungarian forint":"huf",
  "indonesian rupiah":"idr",
  "israeli new sheqel":"ils",
  "manx pound":"imp",
  "indian rupee":"inr",
  "iraqi dinar":"iqd",
  "iranian rial":"irr",
  "icelandic krona":"isk",
  "jersey pound":"jep",
  "jamaican dollar":"jmd",
  "jordanian dinar":"jod",
  "japanese yen":"jpy",
  "yen":"jpy",
  "kenyan shilling":"kes",
  "kyrgystani som":"kgs",
  "cambodian riel":"khr",
  "comorian franc":"kmf",
  "north korean won":"kpw",
  "south korean won":"krw",
  "kuwaiti dinar":"kwd",
  "cayman islands dollar":"kyd",
  "kazakhstani tenge":"kzt",
  "laotian kip":"lak",
  "lebanese pound":"lbp",
  "sri lankan rupee":"lkr",
  "liberian dollar":"lrd",
  "lesotho loti":"lsl",
  "lithuanian litas":"ltl",
  "latvian lats":"lvl",
  "libyan dinar":"lyd",
  "moroccan dirham":"mad",
  "moldovan leu":"mdl",
  "malagasy ariary":"mga",
  "macedonian denar":"mkd",
  "myanma kyat":"mmk",
  "mongolian tugrik":"mnt",
  "macanese pataca":"mop",
  "mauritanian ouguiya":"mro",
  "maltese lira":"mtl",
  "mauritian rupee":"mur",
  "maldivian rufiyaa":"mvr",
  "malawian kwacha":"mwk",
  "mexican peso":"mxn",
  "malaysian ringgit":"myr",
  "mozambican metical":"mzn",
  "namibian dollar":"nad",
  "nigerian naira":"ngn",
  "nicaraguan cordoba":"nio",
  "norwegian krone":"nok",
  "nepalese rupee":"npr",
  "new zealand dollar":"nzd",
  "omani rial":"omr",
  "panamanian balboa":"pab",
  "peruvian nuevo sol":"pen",
  "papua new guinean kina":"pgk",
  "philippine peso":"php",
  "pakistani rupee":"pkr",
  "polish zloty":"pln",
  "paraguayan guarani":"pyg",
  "qatari rial":"qar",
  "romanian leu":"ron",
  "serbian dinar":"rsd",
  "russian ruble":"rub",
  "rwandan franc":"rwf",
  "saudi riyal":"sar",
  "solomon islands dollar":"sbd",
  "seychellois rupee":"scr",
  "sudanese pound":"sdg",
  "swedish krona":"sek",
  "singapore dollar":"sgd",
  "saint helena pound":"shp",
  "sierra leonean leone":"sll",
  "somali shilling":"sos",
  "surinamese dollar":"srd",
  "sao tome and principe dobra":"std",
  "salvadoran colon":"svc",
  "syrian pound":"syp",
  "swazi lilangeni":"szl",
  "thai baht":"thb",
  "thailand baht":"thb",
  "tajikistani somoni":"tjs",
  "turkmenistani manat":"tmt",
  "turkmenistan manat":"tmt",
  "tunisian dinar":"tnd",
  "tunisia dinar":"tnd",
  "tongan paanga":"top",
  "tonga paanga":"top",
  "paanga":"top",
  "turkish lira":"try",
  "turk lira":"try",
  "trinidad and tobago dollar":"ttd",
  "new taiwan dollar":"twd",
  "tanzanian shilling":"tzs",
  "tanzania shilling":"tzs",
  "ukrainian hryvnia":"uah",
  "ukrainia hryvnia":"uah",
  "hryvnia":"uah",
  "ugandan shilling":"ugx",
  "uganda shilling":"ugx",
  "united states dollar":"usd",
  "american dollar":"usd",
  "us dollar":"usd",
  "dollar":"usd",
  "uruguayan peso":"uyu",
  "uruguay peso":"uyu",
  "uzbekistan som":"uzs",
  "venezuelan bolivar fuerte":"vef",
  "venezuelan fuerte":"vef",
  "venezuela fuerte":"vef",
  "fuerte":"vef",
  "vietnamese dong":"vnd",
  "dong":"vnd",
  "vietnam dong":"vnd",
  "vanuatu vatu":"vuv",
  "vatu":"vuv",
  "samoan tala":"wst",
  "tala":"wst",
  "cfa franc beac":"xaf",
  "silver ounce":"xag",
  "silver":"xag",
  "gold ounce":"xau",
  "gold":"xau",
  "east caribbean dollar":"xcd",
  "cfa franc bceao":"xof",
  "palladium ounce":"xpd",
  "cfp franc":"xpf",
  "platinum ounce":"xpt",
  "platinum":"xpt",
  "yemeni rial":"yer",
  "yemen rial":"yer",
  "south african rand":"zar",
  "african rand":"zar",
  "south africa rand":"zar",
  "africa rand":"zar",
  "rand":"zar",
  "zambian kwacha":"zmw",
  "zambia kwacha":"zmw",
  "zimbabwean dollar":"zwl",
  "zimbabwe dollar":"zwl"
}

module.exports.currencies = currencies